/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --env-interface=CloudflareEnv` (hash: 9af49a44fda3183c62191ac149c2c9f5)
interface __BaseEnv_CloudflareEnv {
	BREVO_API_KEY: string;
	QUOTE_TO_EMAIL: string;
	QUOTE_FROM_EMAIL: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BREVO_API_KEY" | "QUOTE_TO_EMAIL" | "QUOTE_FROM_EMAIL">> {}
}
